### ISSUE TITLE
Better indication of Bazel requirement

### ISSUE THREAD

**Issue by nonnontrivial** [node-tensorflow/node-tensorflow#17]
I discovered the need for `Bazel` only after the preinstall script errored.
I would like to augment the documentation (or `build.sh` itself to install `Bazel` if not present on the machine) to make this clear.

Thoughts?

**Comment by tngan** [comment]
@kevmannn Feel free to create a pull request.

**Comment by nonnontrivial** [comment]
@tngan kk!
